### ISSUE TITLE
Module not found: Error: Can't resolve 'autoresponsive-vue'

### ISSUE THREAD

**Issue by liucf** [xudafeng/autoresponsive-vue#3]
import AutoResponsive from 'autoresponsive-vue';

got error:
Module not found: Error: Can't resolve 'autoresponsive-vue'

what's wrong?
please help.

thanks

**Comment by simon300000** [comment]
Same issue

**Comment by xudafeng** [comment]
@liucf @simon300000 

The error is fixed https://github.com/xudafeng/autoresponsive-vue/commit/1dd218071f5e7a41d7661e08009ccbd3bb4ed082,  please  reinstall autoresponsive-vue to the latest version
